CREATE DATABASE IF NOT EXISTS __DB_NAME__;
CREATE USER IF NOT EXISTS '__DB_USER__'@'%' IDENTIFIED BY '__DB_PASS__';
GRANT ALL PRIVILEGES ON __DB_NAME__.* TO '__DB_USER__'@'%';
-- CREATE USER IF NOT EXISTS '__DB_USER__'@'localhost' IDENTIFIED BY '__DB_PASS__';
-- GRANT ALL PRIVILEGES ON __DB_NAME__.* TO '__DB_USER__'@'localhost';
FLUSH PRIVILEGES;
